[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x11/home/g1d3onFr0st)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x1e\0\0\x5\xd1\0\0\x3\xe0\0\0\0\0\0\0\0\x32\0\0\x1\x94\0\0\0\x65\0\0\0\0\x2\0\0\0\x5\xd2\0\0\0\0\0\0\0\x42\0\0\x5\xd1\0\0\x3\xe0)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1490 835)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///run/media/g1d3onFr0st/Storage_USB/p1/New%20folder%20%282%29%20Surgical%20SCORE/SurgicalCORE%20-%20Pilonidal%20cystectomy%2C%20excision%20of%20cyst.flv, file:///run/media/g1d3onFr0st/Storage_USB/p1/New%20folder%20%282%29%20Surgical%20SCORE/SurgicalCORE%20-%20Mastectomy%2C%20Total%20Right%3B%20Recurrent%20Cancer%20of%20the%20Breast.flv, file:///run/media/g1d3onFr0st/Storage_USB/p1/New%20folder%20%282%29%20Surgical%20SCORE/SurgicalCORE%20-%20Pelvic%20Binder.flv, file:///run/media/g1d3onFr0st/Storage_USB/p1/New%20folder%20%282%29%20Surgical%20SCORE/SurgicalCORE%20-%20Chest%20Tube%20Insertion.flv, file:///run/media/g1d3onFr0st/Storage_USB/p1/New%20folder%20%282%29%20Surgical%20SCORE/SurgicalCORE%20-%20Breast%2C%20Needle%20localization%20lumpectomy%3B%20mastectomy%2C%20partial%3B%20ductal%20carcinoma%20in%20situ.flv, file:///run/media/g1d3onFr0st/Storage_USB/p1/New%20folder%20%282%29%20Surgical%20SCORE/SurgicalCORE%20-%20Breast%20Cyst%2C%20Aspiration.flv, file:///run/user/1000/7dc1c1a708d641fc814ba22657cab608/storage/emulated/0/DCIM/13%20angry%20men/9e111ba28c4904c3ee4ee8b23a07b1b2.mp4
times=670419, 622124, 0, 48983, 1428878, 102415, 0
